[package]
name = "uchisliding"
version = "0.8.0"
entrypoint = "lib.typ"
authors = ["skriptum (https://github.com/skriptum)"]
license = "MIT-0"
description = "easy slides in typst - sensible defaults, easy syntax, well styled"
repository = "https://github.com/skriptum/Diatypst"
keywords = ["slides", "presentation", "beamer"]
categories = ["presentation"]
compiler = "0.14.0"
exclude = ["screenshots", "example"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "screenshots/Thumbnail.png"
